#!/bin/bash

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

copy_and_regex() {
	folder_name=$1
	shift

	cp $PROJECT_ROOT/config/base.keymap $PROJECT_ROOT/config/boards/shields/$folder_name/

	while (($# > 0)); do
		regex_text=$1
		shift

		IFS=':' read -r pattern replacement <<<"$regex_text"

		perl -i -pe "s/$pattern/$replacement/g" $PROJECT_ROOT/config/boards/shields/$folder_name/base.keymap
	done

	comment="// This file is automatically generated by $(basename $0) from config/base.keymap"
	perl -i -pe "print \"$comment\n\n\" if $. == 1" $PROJECT_ROOT/config/boards/shields/$folder_name/base.keymap
}

copy_and_regex "chipper42"
copy_and_regex "cb34s"     "K42:   "
copy_and_regex "jnpng28"   "K42:   " "K34:   "
copy_and_regex "jnpng18"   "K42:   " "K34:   " "K28:   " "K22:   "
